Repository bounswe/bounswe2018group1, pull requests merged in 2018-05, with the labels that each got.

#78 Frontend UI added
  twitter project/webserver/src/main/resources/static/index.html
Labels: Position: Review Needed, Priority: High

#84 fixed rate limits
  twitter project/getTrends.py
Labels: Position: Review Needed, Priority: Criticial!!

#80 Changed Backend
  twitter project/Readme.md
  twitter project/ff.py
  twitter project/getTrends.py
  twitter project/trend.py
  twitter project/webserver/.gitignore
  twitter project/webserver/pom.xml
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/TwitterProjectApplication.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/controller/ProjectController.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/core/GlobalExceptionHandler.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/core/SwaggerConfig.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/data/TrendingTopicEntity.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/data/TrendingTopicRepository.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/data/TweetEntity.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/data/TweetRepository.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/model/ProjectException.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/service/ProjectService.java
  twitter project/webserver/src/main/java/com/cmpe352_group1/twitter_project/service/ProjectServiceImpl.java
  twitter project/webserver/src/main/resources/application.properties
  twitter project/webserver/src/main/resources/static/index.html
  twitter project/webserver/src/test/java/com/cmpe352_group1/twitter_project/TrendingTopicRepositoryTests.java
  twitter project/webserver/src/test/java/com/cmpe352_group1/twitter_project/TwitterProjectApplicationTests.java
Labels: Position: Help-wanted, Priority: Criticial!!
